### ISSUE TITLE
Maker panics when triggering two contract setups in parallel

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1071]
I read this on the codebase prior to the executor going in, am on commit: `65b3faa52719a2ec2142aacdb3bc6ee806034844`

Will try to reproduce with current master.

Logs:

```
2022-01-11 17:21:58 TRACE daemon::bitmex_price_feed: Received pong
2022-01-11 17:21:59  INFO rocket::server: POST /api/cfd/ab1e0e6b-14c3-4048-bd29-c53b6300eb5c/acceptOrder:    
2022-01-11 17:21:59 DEBUG daemon::maker_cfd: Maker accepts order order_id=ab1e0e6b-14c3-4048-bd29-c53b6300eb5c
2022-01-11 17:22:00  INFO rocket::server: POST /api/cfd/4d276386-df4d-4a57-a16c-196ba982f97e/acceptOrder:    
2022-01-11 17:22:00 DEBUG daemon::maker_cfd: Maker accepts order order_id=4d276386-df4d-4a57-a16c-196ba982f97e
2022-01-11 17:22:00  INFO daemon::setup_maker: Maker accepts an order order_id=4d276386-df4d-4a57-a16c-196ba982f97e
2022-01-11 17:22:01 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-12T07:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-11 17:22:02  INFO rocket::server: POST /api/cfd/ab1e0e6b-14c3-4048-bd29-c53b6300eb5c/acceptOrder:    
2022-01-11 17:22:02 DEBUG daemon::maker_cfd: Maker accepts order order_id=ab1e0e6b-14c3-4048-bd29-c53b6300eb5c
2022-01-11 17:22:03 TRACE daemon::bitmex_price_feed: No message from BitMex in the last 5 seconds, pinging
2022-01-11 17:22:03 TRACE daemon::bitmex_price_feed: Received pong
2022-01-11 17:22:03  INFO rocket::server: POST /api/cfd/efc9a248-211d-4fa9-b55a-cda10de9c4e7/acceptOrder:    
2022-01-11 17:22:03 DEBUG daemon::maker_cfd: Maker accepts order order_id=efc9a248-211d-4fa9-b55a-cda10de9c4e7
2022-01-11 17:22:03  INFO daemon::setup_maker: Maker accepts an order order_id=efc9a248-211d-4fa9-b55a-cda10de9c4e7
2022-01-11 17:22:04 ERROR daemon::model::cfd: Contract setup failed: Failed to build party params: InsufficientFunds { needed: 704917, available: 0 }
2022-01-11 17:22:06 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-12T07:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-11 17:22:08  INFO daemon::setup_contract: Exchanged setup parameters
2022-01-11 17:22:08 ERROR daemon::maker_inc_connections: No active contract setup order_id=efc9a248-211d-4fa9-b55a-cda10de9c4e7
2022-01-11 17:22:08 TRACE daemon::bitmex_price_feed: No message from BitMex in the last 5 seconds, pinging
2022-01-11 17:22:08 TRACE daemon::bitmex_price_feed: Received pong
2022-01-11 17:22:11 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-12T07:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-11 17:22:11  INFO daemon::setup_contract: Created CFD transactions
2022-01-11 17:22:11  INFO daemon::setup_contract: Exchanged CFD transactions
2022-01-11 17:22:14 TRACE daemon::bitmex_price_feed: No message from BitMex in the last 5 seconds, pinging
2022-01-11 17:22:14 TRACE daemon::bitmex_price_feed: Received pong
2022-01-11 17:22:16 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-12T07:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-11 17:22:16 TRACE daemon::monitor: Updating status of 6 transactions
2022-01-11 17:22:16 TRACE daemon::monitor: Could not find script in own state for txid 539f544898d2e2d0ae8289dc0677ad0df97eb025a9319a5c8a2c5f46723d52b8, ignoring
2022-01-11 17:22:16 TRACE daemon::monitor: Could not find script in own state for txid 539f544898d2e2d0ae8289dc0677ad0df97eb025a9319a5c8a2c5f46723d52b8, ignoring
2022-01-11 17:22:16 TRACE daemon::monitor: CetFinality(OrderId(Hyphenated(c92b84bd-94b2-49a9-9972-0f9f6c528a52))) requires confirmed with 1 blocks and we have unseen
2022-01-11 17:22:16 TRACE daemon::monitor: CetFinality(OrderId(Hyphenated(c92b84bd-94b2-49a9-9972-0f9f6c528a52))) requires confirmed with 1 blocks and we have unseen
2022-01-11 17:22:16 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 2 remaining for this script
2022-01-11 17:22:16 TRACE daemon::monitor: RefundFinality(OrderId(Hyphenated(c92b84bd-94b2-49a9-9972-0f9f6c528a52))) requires confirmed with 1 blocks and we have unseen
2022-01-11 17:22:16 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 1 remaining for this script
2022-01-11 17:22:16 TRACE daemon::monitor: RefundFinality(OrderId(Hyphenated(9e5cfeee-0238-4802-b00c-1cd334a22303))) requires confirmed with 1 blocks and we have unseen
2022-01-11 17:22:16 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 1 remaining for this script
2022-01-11 17:22:16 TRACE daemon::monitor: CommitFinality(OrderId(Hyphenated(9e5cfeee-0238-4802-b00c-1cd334a22303))) requires confirmed with 1 blocks and we have unseen
2022-01-11 17:22:16 TRACE daemon::monitor: CetTimelockExpired(OrderId(Hyphenated(9e5cfeee-0238-4802-b00c-1cd334a22303))) requires confirmed with 12 blocks and we have unseen
2022-01-11 17:22:16 TRACE daemon::monitor: RefundTimelockExpired(OrderId(Hyphenated(9e5cfeee-0238-4802-b00c-1cd334a22303))) requires confirmed with 216 blocks and we have unseen
2022-01-11 17:22:16 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 3 remaining for this script
2022-01-11 17:22:16 TRACE daemon::monitor: LockFinality(OrderId(Hyphenated(9e5cfeee-0238-4802-b00c-1cd334a22303))) requires confirmed with 1 blocks and we have in mempool
2022-01-11 17:22:16 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 1 remaining for this script
2022-01-11 17:22:16 TRACE daemon::monitor: CetTimelockExpired(OrderId(Hyphenated(c92b84bd-94b2-49a9-9972-0f9f6c528a52))) requires confirmed with 12 blocks and we have confirmed with 1 blocks
2022-01-11 17:22:16 TRACE daemon::monitor: RefundTimelockExpired(OrderId(Hyphenated(c92b84bd-94b2-49a9-9972-0f9f6c528a52))) requires confirmed with 216 blocks and we have confirmed with 1 blocks
2022-01-11 17:22:16 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 2 remaining for this script
2022-01-11 17:22:21 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-12T07:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-11 17:22:21 TRACE daemon::bitmex_price_feed: No message from BitMex in the last 5 seconds, pinging
2022-01-11 17:22:22 TRACE daemon::bitmex_price_feed: Received pong
2022-01-11 17:22:26 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-12T07:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-11 17:22:27 TRACE daemon::bitmex_price_feed: No message from BitMex in the last 5 seconds, pinging
2022-01-11 17:22:27 TRACE daemon::bitmex_price_feed: Received pong
2022-01-11 17:22:28  INFO daemon::maker_inc_connections: Upgrade new connection taker_address=127.0.0.1:57405
2022-01-11 17:22:28 DEBUG daemon::noise: Noise protocol responder handshake is complete
2022-01-11 17:22:28  INFO daemon::maker_inc_connections: Connection upgrade successful taker_id=ba4a7001bb1debc4e355f971e7e87409281865691ae64cbd9c8cfac1a07da442 taker_address=127.0.0.1:57405
2022-01-11 17:22:31 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-12T07:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-11 17:22:32 TRACE daemon::bitmex_price_feed: No message from BitMex in the last 5 seconds, pinging
2022-01-11 17:22:32 TRACE daemon::bitmex_price_feed: Received pong
2022-01-11 17:22:35  INFO daemon::setup_contract: Verified all signatures
2022-01-11 17:22:35  INFO daemon::maker_inc_connections: Dropping connection taker_id=ba4a7001bb1debc4e355f971e7e87409281865691ae64cbd9c8cfac1a07da442
thread 'rocket-worker-thread' panicked at '`send_to_taker` only fails if we don't have a HashMap entry. We clean those up together with the heartbeat task. How did we get called without a connection?', daemon/src/maker_inc_connections.rs:277:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: <daemon::maker_inc_connections::Actor as xtra::Handler<daemon::maker_inc_connections::SendHeartbeat>>::handle::{{closure}}
             at ./src/maker_inc_connections.rs:277:9
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
   5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/future/future/map.rs:55:37
   6: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/lib.rs:91:13
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
   8: xtra::context::Context<A>::tick::{{closure}}
             at /Users/dakami/.cargo/git/checkouts/xtra-27dfd36cb04c9fa2/413dc80/src/context.rs:266:17
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  10: xtra::context::Context<A>::run::{{closure}}
             at /Users/dakami/.cargo/git/checkouts/xtra-27dfd36cb04c9fa2/413dc80/src/context.rs:242:19
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:289:9
  13: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/future/future/catch_unwind.rs:36:42
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  15: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  16: <unknown>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:431:6
  17: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  18: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  19: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/future/future/catch_unwind.rs:36:9
  20: <futures_util::future::future::remote_handle::Remote<Fut> as core::future::future::Future>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.19/src/future/future/remote_handle.rs:105:29
  21: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:161:17
  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/loom/std/unsafe_cell.rs:14:9
  23: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:151:13
  24: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:461:19
  25: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  26: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  27: <unknown>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:431:6
  28: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  29: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  30: tokio::runtime::task::harness::poll_future
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:449:18
  31: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:98:27
  32: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:53:15
  33: tokio::runtime::task::raw::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:113:5
  34: tokio::runtime::task::raw::RawTask::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:70:18
  35: tokio::runtime::task::LocalNotified<S>::run
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/mod.rs:343:9
  36: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:443:21
  37: tokio::coop::with_budget::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  39: std::thread::local::LocalKey<T>::with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  40: tokio::coop::with_budget
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  41: tokio::coop::budget
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  42: tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:419:9
  43: tokio::runtime::thread_pool::worker::Context::run
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:386:24
  44: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:371:17
  45: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  46: tokio::runtime::thread_pool::worker::run
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:368:5
  47: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:347:45
  48: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/task.rs:42:21
  49: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:161:17
  50: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/loom/std/unsafe_cell.rs:14:9
  51: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:151:13
  52: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:461:19
  53: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  54: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  55: <unknown>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:438:2
  56: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  57: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  58: tokio::runtime::task::harness::poll_future
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:449:18
  59: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:98:27
  60: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:53:15
  61: tokio::runtime::task::raw::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:113:5
  62: tokio::runtime::task::raw::RawTask::poll
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:70:18
  63: tokio::runtime::task::UnownedTask<S>::run
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/mod.rs:379:9
  64: tokio::runtime::blocking::pool::Inner::run
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/pool.rs:264:17
  65: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/dakami/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/pool.rs:244:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-01-11 17:22:36 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-12T07:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-11 17:22:37 TRACE daemon::monitor: Updating status of 6 transactions

```

**Comment by da-kami** [comment]
Unable to reproduce once the executor went in, but went into another weird error.
