### ISSUE TITLE
Liquidated position (that was not liquidated) causes calculation trouble

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1996]
What happened:

1. The price of Bitcoin tanked, which made one of my positions "liquidated", i.e. 100% loss
2. I tried to collab close this position

The collaborative close failed on the maker side - for the taker it seemingly worked out though, but then the taker ran into multiple issues:

The projecion actor panicked:

```
2022-05-10 00:05:48 DEBUG daemon::db: Applying new events to CFD order_id=6236074d-44e7-41ec-aec6-121b30b682ac aggregate=daemon::projection::Cfd cfd_version=1734 num_events=1
thread 'rocket-worker-thread' panicked at 'Amount to fit into signed amount: TooBig', daemon/src/projection.rs:563:18
```

The `taker_cfd` actor died:

```
2022-05-10 00:06:27  WARN xtras::log_failure: Failed to forward current order from maker: Message handler for message daemon::taker_cfd::CurrentMakerOffers failed: Actor address disconnected
```

--- 

Restart behavior after these errors: 

We keep running into the same problem because of a value that was saved into the db but cannot be handled:

```
thread 'rocket-worker-thread' panicked at 'Amount to fit into signed amount: TooBig', daemon/src/projection.rs:563:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-05-10 00:14:33  WARN xtras::send_async_safe: Async message invocation failed: Actor address disconnected
```

With the projection actor dead one cannot use the taker at all. The UI does not display anything useful because it does not get updates.

**Comment by da-kami** [comment]
values for reproducing the problem:

```
initial_price: 47215
quantity: 100
closing price: 30261
long_leverage 2
short_leverage 1
fee_flow 286 (long pays short)
```
