### ISSUE TITLE
Connection actor can panic on broken clock invariant

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2036]
We can panic  when clock drifts, e.g. when macOS system goes to sleep and awakes itself, syncing with NTP server after coming back online and going "backwards in time".

log:
```
thread 'rocket-worker-thread' panicked at 'clock is monotonic: SystemTimeError(1.454591091s)', daemon/src/connection.rs:102:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'rocket-worker-thread' panicked at 'watch channel should outlive the future: RecvError(())', /home/runner/work/itchysats/itchysats/daemon/src/connection.rs:625:14
```

We should either not panic or supervise the connection actor.

**Comment by klochowicz** [comment]
Retiring heartbeats removes the troublesome code entirely.
