### ISSUE TITLE
Can't take an offer by the taker

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#214]
When I tried taking an offer, I started getting toast notifications with an empty error (`{}`), and noticed the following in the logs:

```
2021-10-06 10:23:54  INFO Taking current order: Order { id: OrderId(fac5f90e-2ecc-45e6-80ef-97956d5b2907), trading_pair: BtcUsd, position: Sell, price: Usd(0), min_quantity: Usd(10), max_quantity: Usd(100), leverage: Leverage(5), liquidation_price: Usd(0), creation_timestamp: SystemTime { tv_sec: 1633477782, tv_nsec: 864544000 }, term: 28800s, origin: Theirs }
2021-10-06 10:23:54  WARN Calculating profit/loss failed. Falling back to 0. division error
2021-10-06 10:23:54  WARN Calculating profit/loss failed. Falling back to 0. division error
2021-10-06 10:23:54  WARN Calculating profit/loss failed. Falling back to 0. division error
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: division error', daemon/src/to_sse_event.rs:178:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'rocket-worker-threadrocket-worker-thread' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: division errorcalled `Result::unwrap()` on an `Err` value: division error', ', daemon/src/to_sse_event.rsdaemon/src/to_sse_event.rs::178178::4242

2021-10-06 10:23:54 DEBUG Taker wants to take an order taker_id=b168235d-d7cd-4631-8529-fb8303acd28b quantity=11 order_id=fac5f90e-2ecc-45e6-80ef-97956d5b2907
2021-10-06 10:23:54  WARN Calculating profit/loss failed. Falling back to 0. division error
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: division error', daemon/src/to_sse_event.rs:178:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bonomat** [comment]
Well... I guess that was introduced by #33 

In your case, it looks like the `price=0` which caused the error.
