### ISSUE TITLE
Several errors during auto-rollover

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#935]
```
2021-12-20 09:11:28  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
2021-12-20 09:11:28 DEBUG daemon::auto_rollover: Not rolled over: The Cfd was just rolled over order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-20 09:11:28  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-20 09:11:30  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-20 09:11:30  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-20 09:11:30  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-20 09:11:30  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:11:33  INFO rocket::server: POST /api/calculate/margin application/json:
thread 'rocket-worker-thread' panicked at 'SelectNextSome polled after terminated', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.18/src/stream/stream/select_next_some.rs:32:9
2021-12-20 09:11:38  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=0509e208-c52a-4fb9-9938-06b0e693f574
thread 'rocket-worker-thread' panicked at 'SelectNextSome polled after terminated', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.18/src/stream/stream/select_next_some.rs:32:9
2021-12-20 09:11:38  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-20 09:11:39  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:11:39  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-20 09:11:39  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-20 09:11:40  INFO rocket::server: POST /api/calculate/margin application/json:
thread 'rocket-worker-thread' panicked at 'SelectNextSome polled after terminated', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.18/src/stream/stream/select_next_some.rs:32:9
thread 'rocket-worker-thread' panicked at 'SelectNextSome polled after terminated', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.18/src/stream/stream/select_next_some.rs:32:9
thread 'rocket-worker-thread' panicked at 'SelectNextSome polled after terminated', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.18/src/stream/stream/select_next_some.rs:32:9
2021-12-20 09:12:15  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:12:16  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:12:34  WARN daemon::auto_rollover: Rollover failed: Expected Msg2 within 60 seconds: deadline has elapsed order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-20 09:12:39  WARN daemon::auto_rollover: Rollover failed: Expected Msg1 within 60 seconds: deadline has elapsed order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-20 09:12:40  WARN daemon::auto_rollover: Rollover failed: Expected Msg1 within 60 seconds: deadline has elapsed order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-20 09:13:10 DEBUG daemon::monitor: Got notification for new block block_height=2132432
2021-12-20 09:13:15  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:13:16  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:14:15  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:14:16  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:15:00  INFO rocket::server: GET /alive:
2021-12-20 09:15:15  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:15:16  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:16:15  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:16:16  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:16:28  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
2021-12-20 09:16:28 DEBUG daemon::auto_rollover: Not rolled over: The Cfd was just rolled over order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-20 09:16:28  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-20 09:16:30  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-20 09:16:30  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-20 09:16:30  INFO daemon::rollover_taker: Rollover proposal got accepted order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-20 09:16:30  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:16:33  INFO rocket::server: POST /api/calculate/margin application/json:
thread 'rocket-worker-thread' panicked at 'SelectNextSome polled after terminated', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.18/src/stream/stream/select_next_some.rs:32:9
2021-12-20 09:16:39  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:16:50 DEBUG daemon::monitor: Found relevant Bitcoin transaction txid=f52f3c1005090f71a7f47119b7d8929e711561c10c6ed7e15fb4cb955bcdb749 status=confirmed with 15 blocks
2021-12-20 09:16:50 DEBUG daemon::monitor: Found relevant Bitcoin transaction txid=a8e671ceb3eaf383bb54a38927e5af64ac05a6cb491ce736e948080a522d69c2 status=confirmed with 15 blocks
2021-12-20 09:16:50  INFO daemon::monitor: Bitcoin transaction reached monitoring target txid=f52f3c1005090f71a7f47119b7d8929e711561c10c6ed7e15fb4cb955bcdb749 target=confirmed with 1 blocks current=confirmed with 15 blocks
2021-12-20 09:16:50  INFO daemon::monitor: Bitcoin transaction reached monitoring target txid=a8e671ceb3eaf383bb54a38927e5af64ac05a6cb491ce736e948080a522d69c2 target=confirmed with 1 blocks current=confirmed with 15 blocks
2021-12-20 09:17:15  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:17:16  INFO rocket::server: POST /api/calculate/margin application/json:
2021-12-20 09:17:34  WARN daemon::auto_rollover: Rollover failed: Expected Msg2 within 60 seconds: deadline has elapsed order_id=0509e208-c52a-4fb9-9938-06b0e693f574
```

Haven't analyzed the logs yet.

**Comment by thomaseizinger** [comment]
More problems when running it longer:

```
2021-12-21 08:27:40 DEBUG daemon::monitor: Got notification for new block block_height=2132650
2021-12-21 08:32:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-21 08:32:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-21 08:32:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-21 08:32:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-21 08:32:18  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
2021-12-21 08:37:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-21 08:37:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-21 08:37:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-21 08:37:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-21 08:37:18  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
2021-12-21 08:42:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-21 08:42:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-21 08:42:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-21 08:42:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-21 08:42:18  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
2021-12-21 08:46:20 DEBUG daemon::monitor: Got notification for new block block_height=2132651
2021-12-21 08:47:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-21 08:47:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-21 08:47:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-21 08:47:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-21 08:47:18  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
2021-12-21 08:52:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-21 08:52:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-21 08:52:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-21 08:52:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-21 08:52:18  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
2021-12-21 08:57:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-21 08:57:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-21 08:57:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-21 08:57:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-21 08:57:18  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
2021-12-21 09:00:01 DEBUG daemon::oracle: Fetching announcement for /x/BitMEX/BXBT/2021-12-22T10:00:00.price?n=20
2021-12-21 09:02:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0f70e537-dc89-4204-9faf-09d63e5a5fc2
2021-12-21 09:02:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=59cbb15a-1519-4c07-8177-6db23ea36bed
2021-12-21 09:02:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=cb2aec3f-c349-4860-938d-23d05285052f
2021-12-21 09:02:18 DEBUG daemon::auto_rollover: Rollover already in progress order_id=0509e208-c52a-4fb9-9938-06b0e693f574
2021-12-21 09:02:18  WARN daemon::auto_rollover: Rollover failed: Cfd does not have a dlc order_id=ef5bec81-664f-40b4-8893-94ecdb765960
```

**Comment by thomaseizinger** [comment]
Most of this seems to be fixed but the rollover logic seems to be flawed:

```
2021-12-30 18:11:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:16:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:21:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:26:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:28:30 DEBUG daemon::monitor: Got notification for new block block_height=2133660
2021-12-30 18:31:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:36:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:41:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:46:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:48:30 DEBUG daemon::monitor: Got notification for new block block_height=2133661
2021-12-30 18:51:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 18:56:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 19:00:00 DEBUG daemon::oracle: Fetching announcement for /x/BitMEX/BXBT/2021-12-31T09:00:00.price?n=20
2021-12-30 19:01:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 19:06:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 19:08:50 DEBUG daemon::monitor: Got notification for new block block_height=2133662
2021-12-30 19:11:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 19:16:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 19:21:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 19:26:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
2021-12-30 19:28:50 DEBUG daemon::monitor: Got notification for new block block_height=2133663
2021-12-30 19:31:50 DEBUG daemon::model::cfd: Rollover was not started: The Cfd was just rolled over order_id=7a00c9cf-9896-4836-b782-c5d1eb4da3c1
```

@da-kami We might need to bring your tests back!

**Comment by da-kami** [comment]
The tests are back, but we still have to confirm that rollover works as expected. 
Given, that I keep running into different problems when testing I'd say we still keep this open until we can confirm that the problems are solved.

**Comment by thomaseizinger** [comment]
Closing, lets see what error pop up until then!
